% -------------------------------------------------------------------
%  Generated by MATLAB on 5-Dec-2025 10:28:35
%  MATLAB version: 9.8.0.1721703 (R2020a) Update 7
% -------------------------------------------------------------------
saveVarsMat = load('final_ramp_step_trapezoidal_tracking_workspace.mat');

Current_Commands = saveVarsMat.Current_Commands; % <6500x1 double> too many elements

Data = saveVarsMat.Data; % <6500x2 double> too many elements

Data_error = saveVarsMat.Data_error; % <6500x1 double> too many elements

Dm_d = saveVarsMat.Dm_d; % <1x1 tf> unsupported class

Dm_s = saveVarsMat.Dm_s; % <1x1 tf> unsupported class

N0 = 6500;

N1 = 500;

N2 = 2000;

N3 = 2500;

N4 = 4000;

N5 = 4500;

T1 = 5;

T2 = 20;

T3 = 25;

T4 = 40;

T5 = 45;

Tcycle = 0.01;

Ts = 0.01;

Xcm = [21.7 20.7 19.7 18.7 17.7 16.7 15.7 14.7 13.7 12.7 11.7 10.7 9.7 ...
       8];

Xvolt = [3.09 3.27 3.36 3.54 3.73 3.97 4.17 4.52 4.87 5.23 5.74 6.45 7.3 ...
         7.82];

channelNamesAI = cell(1, 8);
channelNamesAI{1} = 'Dev1/ai0';
channelNamesAI{2} = 'Dev1/ai1';
channelNamesAI{3} = 'Dev1/ai2';
channelNamesAI{4} = 'Dev1/ai3';
channelNamesAI{5} = 'Dev1/ai4';
channelNamesAI{6} = 'Dev1/ai5';
channelNamesAI{7} = 'Dev1/ai6';
channelNamesAI{8} = 'Dev1/ai7';

channelNamesAO = cell(1, 2);
channelNamesAO{1} = 'Dev1/ao0';
channelNamesAO{2} = 'Dev1/ao1';

cond = 0;

devices = saveVarsMat.devices; % <1x1 daq.ni.DeviceInfo> unsupported class

eq_position = 10.8;

error = 0.078184678819445352;

error_motor = 1.8023575420512414;

fc = 40;

final_position = 17;

final_position2 = 13;

fs = 100;

i = 6500;

i0 = 0.6;

ii = 5;

in1 = 2.66998291015625;

in2 = 5.150146484375;

in3 = 0.00274658203125;

in4 = 0.0018310546875;

in5 = 0.00335693359375;

in6 = -0.00030517578125;

in7 = 0.00396728515625;

in8 = -0.0006103515625;

init_position = 8;

inputDataAI = [-0.0048828125; -0.00579833984375; -0.00640869140625; -0.00579833984375; ...
               -0.0054931640625];

input_motor = 2.4023575420512415;

j = 6500;

ki = 1.834;

kp_m = 4;

kp_r = 1.31;

lengthExp = 65;

numChannelsAI = uint32(8);

numChannelsAO = uint32(2);

outputDataAO = [0 0];

position_cm = 12.921815321180555;

position_ref = saveVarsMat.position_ref; % <6500x1 double> too many elements

prev_error = 0.078184678819445352;

prev_speed_command = 1.4595846520349547;

real_position_cm = saveVarsMat.real_position_cm; % <6500x1 double> too many elements

ref_speed = 1.4595846520349547;

speed_init = 5;

speed_rad = 5.5268646240234371;

speed_reference = saveVarsMat.speed_reference; % <6500x1 double> too many elements

status = int32(0);

t = 0.0007929;

taskHandleAI = uint64(2308556912896);

taskHandleAO = uint64(2308556913336);

time = saveVarsMat.time; % <1x6500 double> too many elements

clear saveVarsMat;
